Bump based CUDA image to ubuntu24.04 (#1166)
Ubuntu24.04 uses `python-3.12` as a main interpreter. Unfortunately, not
all python packages, we use here, has py-3.12 wheel for amd64/arm64, so
need to build the following packages from source:
1. TF-Text
2. Lingvo

Also `python-3.12` added a system-wide protection layer ([PEP
668](https://peps.python.org/pep-0668/)) when install packages using
`pip`:
```
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
```
There are at least 2 possible solutions:
1. install everything into `venv` (the initial solution was proposed by
@olupton).
2. System-wide installation by forcing pip installation with env flag
`PIP_BREAK_SYSTEM_PACKAGES=1`

This branch contains both solutions, but collective mind and experience
of PyTorch team suggests to finalize the second solution (system-wide
installation)

---------

Co-authored-by: Yu-Hang 'Maxin' Tang <Tang.Maxin@gmail.com>