Fix data loaders error for HLO and async in analysis (#2290)
1. Fixing the error `AssertionError: psum_invariant.7.1: message size
calculation for all-reduce has not yet been validated`

This was mainly due because collectives have now an asynchronous
representation:
```
async-start
      └── all-reduce
async-done
```

Therror is that `_get_message_size()` didn't allow to have
`all-gather`/`all-reduce`/`collective-permute`.


2. Trying also to fix this error:
```
KeyError: 'TSL:Thunk:#hlo_op=copy.1,unique_hlo_op_id=4294967297#'
```
here nsys-jax is supposed to convert the full annotation into just
`copy.1` gbut we have a new additional bit added to the thunk. Thus, i'm
modifying the regex we're using for parsing it.