Fix error in AXLearn tests, and remove unnecessary ones (#1443)
This PR does the following: 
- remove `array_serialization_test.py` that's causing the test to hang
with the following error:
```bash 
[pod/axlearn-14925960362-xb57t/axlearn]   File "/opt/jax/jax/experimental/array_serialization/serialization.py", line 193, in __del__
[pod/axlearn-14925960362-xb57t/axlearn]     logger.warning('Please add `.wait_until_finished()` in the main thread '
[pod/axlearn-14925960362-xb57t/axlearn] Message: 'Please add `.wait_until_finished()` in the main thread before your program finishes because there is a possibility of losing errors raised if the this class is deleted before writing is completed.'
[pod/axlearn-14925960362-xb57t/axlearn] Arguments: ()
[pod/axlearn-14925960362-xb57t/axlearn] sssssssssssssss.ssssssssssss.ssssssssssssssssssssssFsFs.s...sssssssFs.Fs [ 97%]
```
causing the EKS job to run out of time - so we can't get the tests 
- remove tests that are redundant (namely, there are similar test
already running) such as:
```bash 
"/opt/axlearn/axlearn/common/deberta_test.py"
"/opt/axlearn/axlearn/common/distilbert_test.py"
"/opt/axlearn/axlearn/common/trainer_test.py"
"/opt/axlearn/axlearn/common/decoder_test.py"
"/opt/axlearn/axlearn/common/adapter_torch_test.py"
"/opt/axlearn/axlearn/common/attention_test.py"
"/opt/axlearn/axlearn/common/convolution_test.py"
```
- remove tests for models that we're not currently using: 
```bash 
"/opt/axlearn/axlearn/common/mixture_of_experts_test.py"
"/opt/axlearn/axlearn/common/t5_test.py"
"/opt/axlearn/axlearn/common/vision_transformer_test.py"
"/opt/axlearn/axlearn/common/input_reading_comprehension_test.py"
"/opt/axlearn/axlearn/common/input_t5_test.py"
```
- remove tests like `summary_writer_test.py` that is mostly using python
library we're not employing here (e.g. `wandb`)
- add the installation of `pytest-xdist` and `pytest-reportlog` to avoid
the following error:
```bash 
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --report-log=/tmp/tmp.iL7rVQtXBq --dist=load --tx --tx 
```

Overall, this should allow us to reduce the testing time from 50 minutes
to 30 minutes, covering the most important tests as well, that are
dealing with general AXLearn infrastructure.

---------

Co-authored-by: Olli Lupton <olupton@nvidia.com>